### ISSUE TITLE
Instruction for cross-compilation

### ISSUE THREAD

**Issue by endorama** [99designs/keyring#23]
Hello, first of all thank you for this project.

I'm trying to cross-compile this package from Linux to MacOSX but I'm having some issues.

My compile instruction is `GOOS=darwin GOARCH=amd64 CGO_ENABLED=1 go build`, but it fails:

```
$ GOOS=darwin GOARCH=amd64 CGO_ENABLED=1 go build
# os/user
.../goenv/versions/1.10/src/os/user/getgrouplist_darwin.go: In function ‘mygetgrouplist’:
.../goenv/versions/1.10/src/os/user/getgrouplist_darwin.go:14:11: warning: implicit declaration of function ‘getgrouplist’ [-Wimplicit-function-declaration]
  int rv = getgrouplist(user, (int) group, buf, ngroups);
           ^
# github.com/99designs/keyring/vendor/github.com/keybase/go-keychain
vendor/github.com/keybase/go-keychain/corefoundation_1.10.go:9:43: fatal error: CoreFoundation/CoreFoundation.h: No such file or directory
compilation terminated.
# net
.../goenv/versions/1.10/src/net/cgo_bsd.go:15:72: could not determine kind of name for C.AI_MASK
```

Is cross-compiling like this possible? 
I tried to compile it with `xgo`, and this "works" ( I didn't tested the resulting binary but at least it compiles ), but I was wondering if you could provide some suggestions/instructions on how to cross-compile this package.

Thank you!

**Comment by mtibben** [comment]
Fixed in #20
