### ISSUE TITLE
github/aulanov/go.dbus versus github.com/godbus/dbus

### ISSUE THREAD

**Issue by paulfurley** [99designs/keyring#30]
It looks like this project uses two DBUS bindings packages:

- [github/aulanov/go.dbus](github/aulanov/go.dbus) (kwallet.go)
- [github.com/godbus/dbus](github.com/godbus/dbus) (libsecret.go)

Is there any reason not to use the same one for both backends?

**Comment by lox** [comment]
Nope, I bet completely by accident.

**Comment by mtibben** [comment]
Fixed in https://github.com/99designs/keyring/commit/4546b610523ea618c5d9dbb3d2714098a411c404
