### ISSUE TITLE
Backend selection is non-deterministic

### ISSUE THREAD

**Issue by henninge** [99designs/keyring#35]
Hi, thanks for the great tool (aws-vault)!

I ran into a problem when not specifying a backend. In that case, the backend is picked from the list provided by `AvailableBackends()`. Unfortunately, that list's order is not deterministic. Here is what I get on consecutive runs:

    [keyring] Considering backends: [keychain pass file]
    ...
    [keyring] Considering backends: [pass keychain file]

As you can tell, I am running this on MacOS and my credentials are stored in keychain. Thus the first run succeeded, the second failed. The reason for this behavior is the  `range supportedBackends` in `AvailableBackends()` which does not guarantee any order on a map.

I can work around this with the `--backend` command line option but an automatic selection would be great. Possible solutions, that I see:

  * Define a fixed order for all supported backends, pass and file bringing up the rear.
  * Define a default backend for each OS and make sure it is first in the list.
  * Or fix the opener for `pass` to fail if it is not configured. That would remedy the current situation (and may be a bug in its on right) but would not make the behavior determnistic.
  * Remove the whole selection code and make `--backend` mandatory.

I am happy to provide a patch for either of these solutions. I'd recommend one of the first two.

**Comment by lox** [comment]
Closed in #36!
