### ISSUE TITLE
Tag as `v1.0.0`

### ISSUE THREAD

**Issue by nickatsegment** [99designs/keyring#49]
The current tag `1.0.0` isn't recognized by go modules; you need a `v` prefix. Without `v` it basically just ignores the tag and we're back to SHA refs.

Related: https://github.com/99designs/keyring/issues/24

**Comment by akerl** [comment]
I guess more specifically, I’d recommend tagging current master as v1.0.1 :D

**Comment by mtibben** [comment]
Fixed
