### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by berniedurfee-ge** [99designs/keyring#5]
I'm getting a compile error when trying to use keyring...

github.com/99designs/keyring/keychain.go:85:16: unknown field 'SelfUntrusted' in struct literal of type keychain.Access

**Comment by berniedurfee-ge** [comment]
I see the issue, the HEAD of keyring is dependent on your unmerged fork.  Dependencies! 😄 

I'm using Dep, so I can workaround this until the merge:

```
[[override]]
  name = "github.com/keybase/go-keychain"
  branch = "master"
  source = "https://github.com/lox/go-keychain.git"
```

**Comment by lox** [comment]
Apologies, I missed this issue! I'm perplexed how you ran into this given that library is vendored in.

**Comment by lox** [comment]
No longer depends on a fork, so closing this!
