### ISSUE TITLE
MacOS keychain support is missing from AvailableBackends list if the binary compiled on Linux

### ISSUE THREAD

**Issue by shoukoo** [99designs/keyring#54]
Does Keyring detect all available backend keys on the current OS in runtime? I am getting different results when executing binaries on macOS but built in different OS environments.

This is the output I got when running on macOS
```
> go run main.go show
keychain
pass
file
```
This is the output after executing the binary built in a Linux container, somehow the keychain is missing in the list when ran on macOS
```
# building a darwin/amd64 binary in Golang Docker image
> docker run -it golang:latest bash -v $PWD/.
> export GOOS=darwin
> export GOARCH=amd64
> export GO111MODULE=on
> go build  
> exit # exit out of the container
> ./bkb show
pass
file
```

**Comment by mtibben** [comment]
Yes this is expected behaviour as Keychain headers are only available on macOS, see https://github.com/99designs/keyring/blob/master/keychain.go#L1 and https://github.com/keybase/go-keychain/blob/master/keychain.go#L1

**Comment by szh** [comment]
Is there a way around this? It doesn't look like https://github.com/zalando/go-keyring has this issue.
Being able to cross compile for macOS would be a huge benefit for automated build systems.
