### ISSUE TITLE
The pass keyring backend doesn't follow symlinks

### ISSUE THREAD

**Issue by stefancocora** [99designs/keyring#62]
Thank you for all the effort dedicated to aws-vault !

My setup is such that the `pass` storage location is behind a symlink
```
ls -lh ~/.password-store

/home/user/.password-store -> /the/real/path/to/.password-store
```
Keyring v1.1.4 is not able to follow the symlink to the password store directory to fetch sensitive information.

Example aws-vault with keyring v1.1.4 failing to retrieve secrets from the `pass` backend

```
aws-vault --version
v5.2.1

aws-vault --backend=pass  exec pers/aws/profiles/testground -- aws sts get-caller-identity
aws-vault: error: exec: Error getting temporary credentials: profile pers/aws/profiles/testground: credentials missing
```

PR to follow.

**Comment by mtibben** [comment]
Can't reproduce this issue. Test added in d531d42
