### ISSUE TITLE
build on ios device found error

### ISSUE THREAD

**Issue by cocoyes** [99designs/keyring#93]
./../go/pkg/mod/github.com/99designs/keyring@v1.1.6/keychain.go:55:8: query.SetMatchSearchList undefined (type keychain.Item has no field or method SetMatchSearchList)
../../go/pkg/mod/github.com/99designs/keyring@v1.1.6/keychain.go:55:28: undefined: keychain.NewWithPath
../../go/pkg/mod/github.com/99designs/keyring@v1.1.6/keychain.go:115:34: undefined: keychain.Keychain
../../go/pkg/mod/github.com/99designs/keyring@v1.1.6/keychain.go:124:12: queryItem.SetMatchSearchList undefined (type keychain.Item has no field or method SetMatchSearchList)
../../go/pkg/mod/github.com/99designs/keyring@v1.1.6/keychain.go:136:8: kcItem.SetAccess undefined (type keychain.Item has no field or method SetAccess)
../../go/pkg/mod/github.com/99designs/keyring@v1.1.6/keychain.go:146:9: undefined: keychain.Keychain
../../go/pkg/mod/github.com/99designs/keyring@v1.1.6/keychain.go:166:9: kcItem.UseKeychain undefined (type keychain.Item has no field or method UseKeychain)
../../go/pkg/mod/github.com/99designs/keyring@v1.1.6/keychain.go:181:9: kcItem.SetAccess undefined (type keychain.Item has no field or method SetAccess)
../../go/pkg/mod/github.com/99designs/keyring@v1.1.6/keychain.go:181:21: undefined: keychain.Access
../../go/pkg/mod/github.com/99designs/keyring@v1.1.6/keychain.go:267:36: undefined: keychain.Keychain
../../go/pkg/mod/github.com/99designs/keyring@v1.1.6/keychain.go:181:21: too many errors

**Comment by cocoyes** [comment]
`sudo CGO_CFLAGS="-I$JAVA_HOME/include -I$JAVA_HOME/include/linux" go build -tags "main evm ios"  -o java/libshare_signer_main.a -ldflags "-s -w" -buildmode=c-archive dechain-go-sdk/mobile`

this is my cmd code

**Comment by juiceppe** [comment]
Same issue here, while trying to install apache-pulsar library

**Comment by pgier** [comment]
Until #102 is merged, the fix for this is to add this directive to your go.mod file.
```
replace github.com/keybase/go-keychain => github.com/99designs/go-keychain v0.0.0-20191008050251-8e49817e8af4
```
